mentor/src/accounts/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from accounts import views as user_views
from django.contrib.auth import views as auth_views
from accounts.views import UserRegisterView, UserBlog, UserFollower, UserView
# from blog.views import UserListView
from .views import (
    UserDetailView,
    UserFollowView,
)

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('search/', UserView.as_view(), name='user_list'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('profile/', user_views.profile, name='profile'),
    path('<username>/', UserDetailView.as_view(), name='account_detail'),
    path('<username>/follow/', UserFollowView.as_view(), name='follow'),
    path('<username>/following/', UserFollower.as_view(), name='following'),# users whom i following
    path('<username>/blog/', UserBlog.as_view(), name='user_blog'),
]

mentor/src/blog/api/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    BlogListAPIView,
    BlogCreateAPIView,
)

urlpatterns = [
    path('', BlogListAPIView.as_view(), name='list'),
    path('create/', BlogCreateAPIView.as_view(), name='create'),
]

mentor/src/blog/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    create_post,
    BlogDetailView,
    BlogDeleteView,
    BlogListView,
    # BlogUpdateView
    update_blog,
    UserBlogListView,
)
urlpatterns = [
    path('', RedirectView.as_view(url="/")),
    path('list/', UserBlogListView.as_view(), name='user_blog_list'), #те на кого подписан
    path('search/', BlogListView.as_view(), name='list'),
    path('create/', create_post, name='create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', update_blog, name='edit'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

mentor/src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


from blog.views import BlogListView
from accounts.views import user_list
from .views import SearchView, about_page, faq, agreement
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('total/', BlogListView.as_view(), name='total'),#общий блог
    path('about/', about_page, name="about"),
    path('faq/', faq, name="faq"),
    path('agreement/', agreement, name="agreement"),
    path('', user_list, name='home'),
    # path('user/search/', SearchView.as_view(), name='search'),#all mentor list
    path('', include(('accounts.urls', 'profiles'), namespace='profiles')),
    path('api/blog/', include(('blog.api.urls', 'blog-api'), namespace='blog-api')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('', include('django.contrib.auth.urls')),
    path('403', views.forbidden_view, name='403'),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentor/src/blog/models.py
from django.conf import settings
from django.db import models
# from accounts.models import User
from django.urls import reverse
from PIL import Image
from accounts.models import User


class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})


class BlogImage(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to='blog_images')
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.blog.title}.jpg'

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 2000 or img.width > 2000:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

mentor/src/blog/forms.py
from django import forms
from .models import Blog, BlogImage


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Your title',
                                            'class': 'form-control'}),
            'content': forms.Textarea(attrs={'placeholder': 'Your post',
                                             'class': 'form-control'}),
        }


class BlogImageForm(forms.ModelForm):
    class Meta:
        model = BlogImage
        fields = ['image', ]
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class DeleteProductForm(forms.Form):
    post_id = forms.IntegerField(widget=forms.HiddenInput(attrs={'class': 'datas'}))

    def clean(self):
        prod_id = self.cleaned_data.get('prod_id')
        if not prod_id:
            raise forms.ValidationError("There is not product id data!")
        if not Blog.objects.filter(id=prod_id).exists():
            raise forms.ValidationError("Such product does not exist!")
        return self.cleaned_data

mentor/src/blog/api/views.py
from django.db.models import Q
from rest_framework import generics
from rest_framework import permissions

from blog.models import Blog

from .pagination import StandardResultsPagination
from .serializers import BlogModelSerializer


class BlogCreateAPIView(generics.CreateAPIView):
    serializer_class = BlogModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class BlogListAPIView(generics.ListAPIView):
    serializer_class = BlogModelSerializer
    pagination_class = StandardResultsPagination

    def get_queryset(self, *args, **kwargs):
        me_following = self.request.user.profile.get_following()
        qs1 = Blog.objects.filter(user__in=me_following)
        qs2 = Blog.objects.filter(user=self.request.user)
        qs = (qs1 | qs2).distinct().order_by("-timestamp")
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs

mentor/src/blog/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.forms import inlineformset_factory
from django.forms.utils import ErrorList
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
                CreateView,
                DetailView,
                DeleteView,
                ListView,
                UpdateView
)

from src.decorators import (
    can_create_blog,
    can_update_blog
)
from .mixins import FormUserNeededMixin, UserOwnerMixin
from .models import Blog, BlogImage
from .forms import *

@can_create_blog
def create_post(request):
    form = BlogForm(request.POST or None)
    BlogImageFormSet = inlineformset_factory(Blog, BlogImage, form=BlogImageForm, extra=1, can_delete=True)
    if request.method == 'POST':
        if form.is_valid():

            user = request.user
            form.instance.user = user
            blog = form.save()
            formset = BlogImageFormSet(request.POST, request.FILES, instance=blog)
            if formset.is_valid():
                formset.save()
            return redirect(blog.get_absolute_url())
    formset = BlogImageFormSet()
    return render(request, 'blog/create_view.html', locals())


@login_required
@can_update_blog
def update_blog(request, id):
    blog = get_object_or_404(Blog, id=id)
    form = BlogForm(request.POST or None, instance=blog)
    title = 'Update a blog'
    BlogImageFormSet = inlineformset_factory(Blog, BlogImage, form=BlogImageForm, extra=0, can_delete=True)
    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            formset = BlogImageFormSet(request.POST, request.FILES, instance=blog)
            if formset.is_valid():
                formset.save()
            return redirect(product.get_absolute_url())
    formset = BlogImageFormSet(instance=blog)
    return render(request, 'blog/update_view.html', locals())


class BlogDeleteView(UserOwnerMixin, UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = "blog/delete_confirm.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        blog = self.get_object()
        if self.request.user == blog.user:
            return True
        return False


class BlogDetailView(DetailView):
    queryset = Blog.objects.all()


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

    def get_queryset(self, *args, **kwargs):
        qs = super(BlogListView, self).get_queryset(**kwargs)
        query = self.request.GET.get("q")
        if query:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            ).order_by("-timestamp")
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(BlogListView, self).get_context_data(*args, **kwargs)
        return context


class UserBlogListView(ListView):
    model = Blog
    template_name = "blog/user_blog_list.html"

    def get_queryset(self, *args, **kwargs):
        qs = Blog.objects.all()
        me_following = self.request.user.profile.get_following()
        qs1 = Blog.objects.filter(user__in=me_following)
        qs2 = Blog.objects.filter(user=self.request.user)
        qs = (qs1 | qs2).distinct().order_by("-timestamp")
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
                           )
        return qs


class UserListView(ListView):
    model = Blog
    template_name = "accounts/user_list_view.html"

    def get_queryset(self, *args, **kwargs):
        qs = super(UserListView, self).get_queryset(**kwargs)
        qs = qs.filter(user=self.user).order_by("-timestamp")
        query = self.request.GET.get("q")
        if query:
            qs = qs.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query)
            ).order_by("-timestamp")
        return qs

mentor/src/blog/templates/blog/blog_detail.html
{% extends "base.html" %} 
{% block title %} Публикация {% endblock title %} 
{% block content %}
<main class="main">
  <div class="background-blobs">
    <svg class="bg-svg" id="blobShape4" viewBox="0 0 500 500">
      <clipPath></clipPath>
      <path
        fill="url(#g4)"
        d="M 274.4,32.13 C 328.5,36.28 249,139.7 287.7,192.8 326.3,245.9 483.3,248.4 459,295 434.9,341.2 341.4,267.6 298,297.5 247.4,332.3 296,461.4 233.9,467.8 177.2,473.8 214.2,326.3 176,268.3 137.8,210.5 24.39,242.4 39.89,189.3 54.21,140.1 142,158.9 184.6,129.2 221.1,103.9 229.3,28.68 274.4,32.13 Z"
      />
      <linearGradient id="g4" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0" stop-color="#fa7166" />
        <stop offset="1" stop-color="#fd964b" />
      </linearGradient>
    </svg>
    <section>
      <div class="container publication">
        <div class="col-sm-12 col-lg-8 col-md-8">
          <div class="publication-card">
            <h4 class="font-title">
              {{ object.title }}
            </h4>
            <p class="font-text-sm">{{ object.timestamp | timesince }}</p>
            <div class="publication-card__img">
              <img src="{{ object.blogimage_set.first.image.url }}" alt="" />
            </div>
            <p class="font-text">
              {{ object.content }}
            </p>
            {% if object.user == request.user %}
            <div class="publication-card__footer">
              <a href="{% url 'blog:edit' object.id %}">
                <div
                  class="publication-card__footer__icon"
                  id="icon-edit"
                ></div>
              </a>
              <a href="{% url 'blog:delete' object.id %}">
                <div
                  class="publication-card__footer__icon"
                  id="icon-delete"
                ></div>
              </a>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="publication-author-card col-sm-12 col-lg-4 col-md-4">
          <div class="publication-author-card__card-header">
            <h4 class="font-title-sm">Автор публикации</h4>
          </div>
          <div class="publication-author-card__card-body">
            <div class="publication-author-card__card-body__author">
              <div class="publication-author-card__card-body__author__avatar">
                  <img src="{{ object.user.profile.image.url }}">
              </div>
              <div class="publication-author-card__card-body__author__name">
                <h5 class="font-text">
                  <a href="{% url 'profiles:account_detail' object.user.username %}"
                    >{{ object.user.first_name }} {{ object.user.last_name }}</a
                  >
                </h5>
                <p class="font-text-sm">{{ object.user.position }}</p>
              </div>
            </div>
            <p
              class="publication-author-card__card-body__card-body__content font-text"
            >
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. At odio
              praesentium harum ducimus quis porro. Soluta quia odio tempore
              nisi reiciendis facilis expedita, consectetur nam voluptas ab
              reprehenderit ad recusandae!
            </p>
          </div>
        </div>
      </div>
    </section>
  </div>
</main>
{% endblock content %}

mentor/src/blog/templates/blog/blog_list.html
{% extends "base.html" %}
{% block title %} Блог {% endblock title %} 
{% block content %}
    <main class="main">
        <div class="background-blobs">

            <svg class="bg-svg" id="blobShape3" viewBox="0 0 500 500">
                <clipPath></clipPath>
                <path
                        fill="url(#g3)"
                        d="M 402.7,215.5 C 433.9,280.4 488.1,367.2 447.7,426.8 410.1,482.2 316.7,460.2 249.7,460.6 182.8,461.1 88.08,485.5 51.26,429.5 10.29,367.3 73.19,279.4 106.9,213 141.8,144 176.6,33.65 253.9,33.7 332.2,33.75 368.8,144.9 402.7,215.5 Z"
                />
                <linearGradient id="g3" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0" stop-color="#94d6ba" />
                    <stop offset="1" stop-color="#b5a9c4" />
                </linearGradient>
            </svg>
            <section>
                <div
                        class="container col-lg-8 col-md-10 col-sm-12"
                        id="blog__blog-cards"
                >
                    <h2 class="font-title">Блог сообщества</h2>
                    <p class="font-text">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Perspiciatis commodi alias nisi, velit repudiandae perferendis
                        delectus exercitationem numquam ducimus cumque.
                    </p>
                    <form method="GET" id="blog__search-form" action="{% url 'blog:list' %}">
                        <div class="searchbox col-lg-8 col-md-8 col-sm-12">
                            <input
                                    type="text"
                                    class="searchbox__input font-text"
                                    placeholder="Поиск"
                                    name="q"
                                    value="{{ request.GET.q }}"
                            />
                            <input type="submit" class="searchbox__icon" value="" />
                        </div>
                    </form>
                    {% for object in object_list %}
                        <div class="blog-card">
                            <div class="blog-card__blog-card-header">
                                <div class="blog-card__blog-card-header__avatar" alt="">
                                    <img src="{{ object.user.profile.image.url }}">
                                </div>
                                <div class="blog_card__blog-card-header__username">
                                    <h4 class="font-subtitle"><a href="{% url 'profiles:account_detail' object.user.username %}">{{ object.user.first_name }} {{ object.user.last_name }}</a></h4>
                                    <p class="font-text-sm">{{ object.timestamp|timesince }}</p>
                                </div>

                            </div>
                            <div class="blog-card__blog-card-body">
                                <h4 class="font-title-sm">
                                    <a href="{% url 'blog:detail' object.id %}"
                                    >{{ object.title }}</a
                                    >
                                </h4>
                                <p class="font-text">
                                    {{ object.content | truncatechars:100 }}
                                </p>
                                <div class="blog-card__blog-card-body__img">
                                    <img src="{{ object.blogimage_set.first.image.url }}" alt="" />
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        {% if request.GET.q %}
                            <p class="mt-5 mb-5 font-text col-6 offset-3" style="text-align:center">Мы не нашли такой пост((</p>
                        {% else %}
                            <p class="mt-5 mb-5 font-text col-6 offset-3" style="text-align:center">Пока постов нет</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>

{% endblock content %}

mentor/src/blog/templates/blog/create_view.html
{% extends "base.html" %}
{% block title %}
    Создать пост
{% endblock title %}
{% block content %}
    <div class="container d-block mx-auto mt-5">
        <h2 class="font-title">Создать пост</h2>
        <form method="post" enctype="multipart/form-data" .>
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ formset.management_form }}
                {{ formset.non_form_errors }}
                {% for form in formset.forms %}
                {% if forloop.first %}
                <thead>
                    <tr>
                        {% for field in form.visible_fields %}
                        <th>{{ field.label|capfirst }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                {% endif %}
                <tr class="formset_row">
                    {% for field in form.visible_fields %}
                    <td>
                        {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                        {% endif %}

                        {{ field.errors.as_ul }}
                        {{ field }}
                    </td>
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
            <button type="submit" class="btn btn-success d-block mx-auto">Create a post</button>
        </form>
    </div>
{% endblock content %}

mentor/src/blog/templates/blog/delete_confirm.html
{% extends "base.html" %}
Delete confirm
{% block content %}
    <div class="container pb-5 pt-5">
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <h2 class="font-title-sm mb-5 mt-5">Вы уверены, что хотите удалить пост "{{ object.title }}"</h2>
                <div class="form-group mb-5">
                    <button class="btn btn-white mr-3 mt-3" type="submit">Да, удалить</button>
                    <a class="btn btn-primary mt-3" href="{% url 'blog:detail' object.id %}">Отмена</a>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

mentor/src/blog/templates/blog/form.html
{#{% load crispy_forms_tags %}#}
{#<form {% if form_id %}id="{{ form_id }}"{% endif %}class="form mt-2" method="POST" action="{% if action_url %}{{ action_url }}{% endif %}">#}
{#    {% csrf_token %}#}
{#    {{ form|crispy }}#}
{#    <input class="btn btn-primary" type="submit" value="{{ btn_title }}">#}
{#</form>#}
{#<div class="container">#}
{#    <div class="content-section">#}
{#        <form method="POST" enctype="multipart/form-data">#}
{#            {% csrf_token %}#}
{#            <fieldset class="form-group">#}
{#                <legend class="border-bottom mb-4">Blog Post</legend>#}
{#                {{ form.as_p}}#}
{#                {{ formset.management_form }}#}
{#                {{ formset.non_form_errors }}#}
{#                {% for form in formset.forms %}#}
{#                {% if forloop.first %}#}
{#                <thead>#}
{#                    <tr>#}
{#                        {% for field in form.visible_fields %}#}
{#                        <th>{{ field.label|capfirst }}</th>#}
{#                        {% endfor %}#}
{#                    </tr>#}
{#                </thead>#}
{#                {% endif %}#}
{#                <tr class="formset_row">#}
{#                    {% for field in form.visible_fields %}#}
{#                    <td>#}
{#                        {% if forloop.first %}#}
{#                        {% for hidden in form.hidden_fields %}#}
{#                        {{ hidden }}#}
{#                        {% endfor %}#}
{#                        {% endif %}#}
{##}
{#                        {{ field.errors.as_ul }}#}
{#                        {{ field }}#}
{#                    </td>#}
{#                    {% endfor %}#}
{#                </tr>#}
{#                {% endfor %}#}
{#            </fieldset>#}
{#            <div class="form-group">#}
{#                <input class="btn btn-primary" type="submit" value="{{ btn_title }}">#}
{#            </div>#}
{#        </form>#}
{#    </div>#}
{#</div>#}

mentor/src/blog/templates/blog/search_form.html
<form id="navbar-search-form" class="form-inline" method="GET" action="{% url 'search' %}">
    <div class="form-group">
    <input class="form-control " type="text" name="q" placeholder="search" value="{{ request.GET.q }}">
    </div>

    <button class="btn btn-outline-secondary ml-2" type="submit">Search</button>
</form>

mentor/src/blog/templates/blog/update_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Редактировать пост{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto">
                <h1 class="text-center font-title">Редактировать пост</h1>
                <form method="post" enctype="multipart/form-data" class="mb-5">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <table class="table">
                        {{ formset.management_form }}
                        {{ formset.non_form_errors }}
                        {% for form in formset.forms %}
                            {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                            {% endif %}
                            <tr class="formset_row">
                                {% for field in form.visible_fields %}
                                <td>
                                    {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                    {% endfor %}
                                    {% endif %}

                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <button type="submit" class="btn btn-primary d-block mx-auto">Update the blog</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: '<button class="btn btn-info mt-3">Add new image</button>',
            deleteText: '<button class="btn btn-danger">Delete</button>',
            prefix: 'blogimage_set',
        });
    </script>
{% endblock js %}

mentor/src/blog/templates/blog/user_blog_list.html
{% extends "base.html" %}

{% block title %}
    Моя лента
{% endblock title %}

{% block content %}
    <main class="main">
        <div class="background-blobs">
            <svg class="bg-svg" id="blobShape3" viewBox="0 0 500 500">
                <clipPath></clipPath>
                <path
                        fill="url(#g3)"
                        d="M 402.7,215.5 C 433.9,280.4 488.1,367.2 447.7,426.8 410.1,482.2 316.7,460.2 249.7,460.6 182.8,461.1 88.08,485.5 51.26,429.5 10.29,367.3 73.19,279.4 106.9,213 141.8,144 176.6,33.65 253.9,33.7 332.2,33.75 368.8,144.9 402.7,215.5 Z"
                />
                <linearGradient id="g3" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0" stop-color="#94d6ba" />
                    <stop offset="1" stop-color="#b5a9c4" />
                </linearGradient>
            </svg>
            <section>
                <div class="container col-lg-8 col-md-10 col-sm-12" id="blog__blog-cards">
                    <h2 class="font-title">Моя Лента</h2>
                    <p class="font-text">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
                        commodi alias nisi, velit repudiandae perferendis delectus
                        exercitationem numquam ducimus cumque.
                    </p>
                    {% for object in object_list %}
                        <div class="blog-card">
                            <div class="blog-card__blog-card-header">
                                <img
                                        class="blog-card__blog-card-header__avatar"
                                        src="{{ object.user.profile.image.url }}"
                                />
                                <div class="blog_card__blog-card-header__username">
                                    <h4 class="font-subtitle">
                                        <a href="/{{ object.user.username}}/">{{ object.user.first_name }} {{ object.user.last_name }}</a>
                                    </h4>
                                    <p class="font-text-sm"> {{ object.timestamp | timesince }}</p>
                                </div>
                            </div>
                            <div class="blog-card__blog-card-body">
                                <h4 class="font-title-sm">
                                    <a href="{% url 'blog:detail' object.id %}">{{ object.title }}</a>
                                </h4>
                                <p class="font-text blog-card__blog-card-body_text">{{ object.content | truncatechars:100 }}</p>
                                <div class="blog-card__blog-card-body__img">
                                    <img src="{{ object.blogimage_set.first.image.url }}"/>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        </div>
    </main>
{% endblock content %}